### PR TITLE
Add module existence check.

### LINKED ISSUE #15: Error: Uncaught ReferenceError: module is not defined
Exporting module:
```
module.exports = {
  JsonApiDataStore: JsonApiDataStore,
  JsonApiDataStoreModel: JsonApiDataStoreModel
};
```
Not works in non-nodejs and non-browserify environments. There is no need to always use requirejs and stuff like that. I'm suggesting add `module` existance check. I'm ready to create PR if you agree.

### PR DESCRIPTION
**Pull request by mklocek**
Added `module` existance check to make JsonApiDataStore work with non-nodejs and/or non-browserify environments without exceptions.

### CODE REVIEW

**Comment by beauby** [comment]
LGTM, merging!

**Comment by omnikrll** [comment]
Hi,

When I installed jsonapi-datastore through Bower this change was not reflected- I ran into this same problem and ended up implementing this fix manually. Is the bower.json correct?

Thanks,
Karl

**Comment by ahmadhsalim** [comment]
same thing on my side, the module existence check isn't there.

**Comment by mklocek** [comment]
@ahmadhsalim you need to use github master branch until @beauby releases new bower version

**Comment by beauby** [comment]
Hi guys, sorry about that, I kinda forgot about bower once I set up the automated npm deploy. Will release a new bower version ASAP.

**Comment by beauby** [comment]
Just released a new bower version.

**Pull request merged**
