### PR TITLE
Convert to ES6

### PR DESCRIPTION
**Pull request by jprincipe**
@beauby resolved the merge issues form the last PR

### CODE REVIEW

**Comment by jprincipe** [comment]
@beauby I have another PR coming based off of ES6 to add support for meta data.  After you accept this PR I'll submit the next one.

**Comment by beauby** [comment]
@jprincipe Thanks for the rebase (for future reference, you can `git rebase` and `git push -f` for squashing so that you don't have to create a new PR).
Is there a technical reason why you merged `store.js` and `model.js` into a single file?

**Comment by jprincipe** [comment]
It was to avoid an issue that babel was having with `store.js` referencing `model.js`.  The minified version of the file didn't know what to do with the reference because after minification `model.js` doesn't exist.

**Comment by beauby** [comment]
@jprincipe Sorry it took so long, I've been really busy with ActiveModel::Serializers lately. One last question before merge: does this PR play nice with the angular wrapper?

**Comment by jprincipe** [comment]
I haven't tested the angular wrapper specifically, but all the code is converted from es6 before so there should be no issues

**Comment by beauby** [comment]
Ok great, merging then. Thanks a lot!

**Pull request merged**
