### PR TITLE
convert to ES6

### PR DESCRIPTION
**Pull request by jprincipe**
Convert JsonApiDataStore and JsonApiDataStoreModel to classes.
Update mocha tests to to use new import and function syntax.
Use babel to convert dist files ES5.

### CODE REVIEW

**Comment by beauby** [comment]
Hey @jprincipe, could you rebase this so that I can merge it?

**Comment by jprincipe** [comment]
@beauby rebase is complete

**Comment by beauby** [comment]
Thanks a lot, could you just squash your commits into one so that we keep the history clean?

**Comment by jprincipe** [comment]
@beauby closed this PR and opened another one with all commits squashed

**Pull request closed without merging**
